backend:
  name: git-gateway
  branch: main
  
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

publish_mode: editorial_workflow

collections:
  - name: "stories"
    label: "Stories"
    label_singular: "Story"
    folder: "_stories"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", default: []}
      - {label: "Length", name: "length", widget: "string", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Cover Image", name: "cover", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: updates
    label: Boardgame Updates
    folder: "_updates"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime }
      - { label: Summary, name: excerpt, widget: text }
      - { label: Body, name: body, widget: markdown }

  - name: projects
    label: Portfolio
    folder: "_projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime }
      - { label: Tags, name: tags, widget: list, default: [] }
      - { label: Links, name: links, widget: list, field: { label: URL, name: url, widget: string }, required: false }
      - { label: Cover, name: cover, widget: image, required: false }
      - { label: Body, name: body, widget: markdown }