backend:
  name: github
  repo: sarkanynexus/Main_Site   # <-- change this
  branch: main
  base_url: https://github.com
  app_id: Ov23li4eFMve5bgiG9qk
  
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

publish_mode: editorial_workflow

collections:
  - name: "stories"
    label: "Stories"
    label_singular: "Story"
    folder: "_stories"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", default: []}
      - {label: "Length", name: "length", widget: "string", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Cover Image", name: "cover", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
